USE farmacia_archimede;
INSERT INTO product_types (name, description) VALUES
    ('Medicinale', 'Farmaci e prodotti ad azione terapeutica'),
    ('Cosmetico', 'Prodotti per la cura e l\'igiene della persona'),
    ('Integratore', 'Integratori alimentari e vitamine');

INSERT INTO users (email, password_hash, first_name, last_name, tax_code, is_admin) VALUES
    ('utente@utente.it', '$2y$10$aMaKtkEfsdymuc.jj5ZGw.tPql6lSjckmxndSZuyqHPnOH0A5hn9y', 'utente', 'utente', 'utenteutente', 0),
    ('admin@admin.it', '$2y$10$iQKwz.lhMxk6E0f2S68nn.7trjjGTBnYRjPqv/VX3VrQftVvSm6hS', 'admin', 'admin', 'adminadmin', 1);

INSERT INTO products (product_type_id, short_name, name, manufacturer, aic_code, format, price, availability, description, image_path) VALUES
    (1, 'Aspirina C Antidolorifico e Antinfiammatorio',
        'Aspirina C Antinfiammatorio Antidolorifico per Influenza Raffreddore e Febbre con Vitamina C 40 cpr',
        'Bayer', '004763619', 'compresse', 13.05, 500,
        '40 compresse. Aspirina C Compresse Effervescenti si usa nella terapia sintomatica degli stati febbrili e delle sindromi influenzali e da raffreddamento e nel trattamento sintomatico di mal di testa e di denti, nevralgie, dolori mestruali, dolori reumatici e muscolari.',
        'aspirinac_antinfiammatorio.webp'),
    (1, 'Buscopopan Mal di Pancia e Dolori Addominali',
        'Buscopan Per Mal di Pancia Crampi Dolori Addominali 40 Compresse',
        'Opella Healthcare Italy S.r.l.', '006979088', 'compresse', 16.90, 1465,
        '40 compresse. Buscopan è un medicinale a base di N-butilbromuro di Joscina. È indicato per il trattamento del mal di pancia, in caso di crampi e dolori addominali. Agisce direttamente all’origine dei crampi, nell’addome, per fermare il dolore che può essere causato da: eccesso di cibo, alimentazione scorretta, stress, ansia.',
        'buscopan_compresse.webp'),
    (2, 'CeraVe Crema Viso Idratante',
        'CeraVe Crema Viso Idratante SPF50 50ml',
        'Cerave', '983679578', 'crema', 18.89, 6542,
        'CeraVe Crema Viso Idratante SPF 50 è una crema per il viso leggera e idratante per un uso quotidiano, con una protezione SPF 50 alta contro i raggi UVB/UVA e 3 ceramidi essenziali per aiutare a proteggere la barriera naturale della pelle e lasciare la pelle lenita e idratata fino a 24 ore.',
        'cerave_cremaviso.webp'),
    (1, 'Froben Gola Nebulizzatore',
        'Froben Gola Nebulizzatore Spray 15ml',
        'Viatris', '042822027', 'spray', 12.30, 562,
        'Froben Gola si usa nel trattamento sintomatico di stati irritativo-infiammatori anche associati a dolore del cavo orofaringeo (ad es. gengiviti, stomatiti, faringiti), anche in conseguenza di terapia dentaria conservativa o estrattiva.',
        'frobengola_nebulizzatore.webp'),
    (2, 'La Roche Posay Anti-Rughe',
        'La Roche Posay Hyalu B5 Siero Anti-Rughe 30ml Acido Ialuronico',
        'La Roche Posay', '973042106', 'gel', 47.49, 62,
        'Il siero La Roche Posay Hyalu B5 è studiato per affrontare i segni dell\'invecchiamento della pelle, con un focus particolare sulla riduzione di rughe e linee sottili. Grazie alla sua formula innovativa, questo siero restituisce vitalità alla pelle, rendendola subito più elastica e donandole un aspetto fresco e luminoso. È particolarmente indicato per chi nota una diminuzione dell\'elasticità e un colorito opaco, offrendo un\'azione efficace nel rimpolpare e rigenerare.',
        'laroche_antirughe.webp'),
    (3, 'Vitamina C Liquida',
        'Vitamina C Liquida + D3 con Zinco 500ml',
        'NatuGea', '973452245', 'sciroppo', 31.90, 6543,
        'Vitamina C + D3 con Zinco è un integratore alimentare concentrato in forma liquida, formulato appositamente per la la normale funzione del sistema immunitario. La Vitamina C contribuisce: alla normale funzione del sistema immunitario, alla protezione delle cellule dallo stress ossidativo, alla normale formazione del collagene per la normale funzione di pelle, ossa, denti, gengive, cartilagini e vasi sanguigni e aiuta a ridurre la stanchezza e l\'affaticamento.',
        'natugea_vitaminac.webp'),
    (3, 'Natural Point integratore Magnesio',
        'Natural Point integratore alimentare Magnesio supremo 300 g',
        'Natura Point', '905972081', 'compresse', 22.13, 95,
        'Trecentoventicinque funzioni vitali si attivano in presenza del magnesio, che è un elemento straordinario e senza eguali fra tutti i minerali utili all\'organismo. Col magnesio, il nostro corpo si regola come il meccanismo di precisione di un orologio. Ma se il magnesio scarseggia, certe funzioni chiave si inceppano: l\'equilibrio tra calcio, potassio e sodio, la formazione delle proteine, l\'energia delle cellule, il livello del glucosio.',
        'naturapoint_magnesio.webp'),
    (2, 'Nivea Dry Comfort Deodorante Roll on',
        'Nivea Dry Comfort Deodorante Roll on Antitraspirante 72h Con Formula Dual Active 50ml',
        'Nivea', '975940178', 'gel', 3.12, 51,
        'Il deodorante antitraspirante Nivea Dry Comfort regola efficacemente la traspirazione per 72 ore e garantisce una piacevole sensazione di pelle protetta e asciutta per tutto il giorno. La sua formula innovativa Dual Active con doppio anti-traspirante testato nella vita reale assicura una duratura sensazione d\'asciutto e freschezza sulla cute, una combinazione ottimale di massima efficacia e delicatezza Nivea. Grazie alla formula priva di alcool etilico e oli minerali, l\'antitraspirante ascelle limita le irritazioni dell\'epidermide. La formula è dermotestata e approvata da AIDECO, Associazione Italiana di Dermatologia e Cosmetologia. Non applicare su pelle lesa o irritata.',
        'nivea_drycomfort.webp'),
    (2, 'Nivea Sun Latte Solare Protect & Hydrate Fp50+',
        'Nivea Sun Latte Solare Protect & Hydrate Fp50+ Crema Solare Idratante in Formato Viaggio 100ml',
        'Nivea', '979015930', 'gel', 7.19, 5135,
        'Nivea Sun Latte Solare Protect & Hydrate FP50+ è una crema solare con formula 5in1: protegge dai raggi Uva e UV, resiste all\'acqua, dona 48 ore di idratazione, ha una formula biodegradabile e mantiene in equilibrio il microbioma, ovvero il delicato ecosistema cutaneo che agisce da sua barriera difensiva. Inoltre, questo latte solare offre alla pelle protezione immediata dalle scottature e dall\'invecchiamento precoce.',
        'nivea_sunprotect.webp'),
    (3, 'Nova Vitamina D',
        'Nova Vitamina D 80 Compresse',
        'Nova Argentia srl Ind Farm', '982946586', 'compresse', 5.48, 0,
        'Nova.D è un integratore alimentare a base di vitamina D che: contribuisce alla normale funzione del sistema immunitario, contribuisce al normale assorbimento/utilizzo del calcio e del fosforo, contribuisce al mantenimento di normali livelli di calcio nel sangue e di ossa normali, contribuisce al mantenimento della normale funzione muscolare, contribuisce al mantenimento di denti normali, interviene nel processo di divisione delle cellule.',
        'nova_vitaminad.webp'),
    (1, 'Okitask 40mg Senza Acqua',
        'OKITask 40mg granulato senza acqua 30 bustine orosolubili',
        'Dompe', '042028050', 'polvere', 10.49, 1000,
        '30 bustine orosolubili. Okitask in bustine orosolubili appartiene alla categoria dei farmaci antinfiammatori e antireumatici.',
        'okitask_granulatonoacqua.webp'),
    (2, 'Somatoline Body-Lift',
        'Somatoline Body-Lift Crema Seno',
        'Somatoline', '022816060', 'crema', 18.75, 356,
        'Trattamento ad azione liftante specificatamente studiato per agire in modo mirato sulla zona del seno. La sua nuova formula pro-collagene è arricchita con attivi rimpolpanti e specifici principi attivi che aiutano a rinforzare la struttura della pelle stimolando la produzione di collagene, ricompattare e rimpolpare la pelle del seno.',
        'somatoline_skinexpert.webp'),
    (3, 'Supradyn Ricarica Integratore Multivitaminico',
        'Supradyn Ricarica Integratore Multivitaminico Completo e Minerali con Coenzima Q10 60 Compresse',
        'Bayer', '935662611', 'compresse', 21.75, 356,
        'La formula specifica con vitamine e minerali di Supradyn® Ricarica è stata sviluppata per contrastare l\'affaticamento fisico e integrare il mancato apporto giornaliero di micronutrienti, per sentirsi pieni di energia ogni giorno.',
        'supradyn_ricarica.webp'),
    (2, 'Vichy Dercos Shampoo Antiforfora',
        'Vichy Dercos Shampoo Antiforfora Capelli Grassi 390 ml',
        'Dercos', '926568179', 'gel', 19.23, 756,
        'Formula avanzata con Peptidi pro -collagene di tipo I e II e Vitamina Cg associati all\'Acqua Vulcanica di Vichy per correggere i segni della perdita di collagene sulla pelle. Questa crema è consigliata per chi cerca un\'elevata efficacia anti -età e l\'attenzione nel prendersi cura della pelle.',
        'vichy_antiforfora.webp'),
    (1, 'Voltaren Emulgel 2% Antinfiammatorio',
        'Voltaren Emulgel 2% Antinfiammatorio Diclofenac Dolori Articolari Mal Di Schiena Gel 100 g',
        'Gsk', '034548154', 'gel', 15.93, 75,
        'Voltaren Emulgel 2% Gel è un farmaco antinfiammatorio di automedicazione indicato nel trattamento dei dolori reumatici e articolari. La concentrazione al 2% del suo principio attivo agisce sull\'infiammazione fino a 12 ore, offrendoti un sollievo prolungato nel tempo.',
        'voltaren_antinfiammatorio.webp'),
    (3, 'ZzzQuil Pastiglie Gommose Melatonina',
        'ZzzQuil NATURA 60 Pastiglie Gommose Melatonina Camomilla',
        'Vicks', '976597070', 'compresse', 17.97, 754,
        'Integratore per il sonno, ZzzQuil NATURA: 60 pastiglie gommose a base di melatonina con camomilla, valeriana e lavanda.',
        'zzzquil_melatonina.webp');
